from typing import Literal
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    role: Literal["user", "assistant", "system"]
    content: str


class AssistantRequest(BaseModel):
    message: str = Field(min_length=1, max_length=4000)
    history: list[ChatMessage] = []
    user_id: int | None = None
    anon_id: str | None = None


class AssistantCitation(BaseModel):
    source: str
    title: str
    url: str | None = None


class SuggestedAction(BaseModel):
    """A clickable follow-up the chat surfaces below an answer.

    Handlers populate this when there's a concrete next step ("View
    pricing", "Open ECO on pmi.org"). The frontend renders each as a
    button that either navigates internally (if url starts with '/')
    or opens externally.
    """
    label: str
    url: str


class AssistantResponse(BaseModel):
    # AssistantLog row id for this turn. Lets the widget reference the
    # specific turn when the user flags it ("Wasn't helpful?"). Optional
    # so older clients that don't expect it still parse responses cleanly.
    turn_id: int | None = None
    # Legacy keyword classifier emits one of the five handler-intent
    # values. The agentic flow emits the literal "agentic" instead —
    # the response carries no per-handler intent (the router chose
    # tools, not an intent), so we surface the flow name in this slot
    # to keep the wire shape consistent across both flows. The
    # frontend's AssistantWidget doesn't currently branch on this
    # field, but a future "render differently per flow" treatment
    # would key off "agentic" here.
    intent: Literal[
        "account", "faq", "content", "insights", "pmi_reference",
        "agentic",
    ]
    intent_confidence: float
    message: str
    citations: list[AssistantCitation] = []
    # Was `list[str]`; handlers actually return {label, url} dicts.
    # The richer shape lets the frontend render buttons that link
    # somewhere — strings alone produced unclickable chips.
    suggested_actions: list[SuggestedAction] = []
    provider: str
    model_version: str | None = None
    is_ai_generated: bool = True
    disclaimer: str = (
        "This response was generated by AI and may be inaccurate. "
        "Verify critical information with the official CPMAI handbook."
    )
