from typing import Literal
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    role: Literal["user", "assistant", "system"]
    content: str


class AssistantRequest(BaseModel):
    message: str = Field(min_length=1, max_length=4000)
    history: list[ChatMessage] = []
    user_id: int | None = None
    anon_id: str | None = None


class AssistantCitation(BaseModel):
    source: str
    title: str
    url: str | None = None


class AssistantResponse(BaseModel):
    intent: Literal["account", "faq", "content", "insights"]
    intent_confidence: float
    message: str
    citations: list[AssistantCitation] = []
    suggested_actions: list[str] = []
    provider: str
    model_version: str | None = None
    is_ai_generated: bool = True
    disclaimer: str = (
        "This response was generated by AI and may be inaccurate. "
        "Verify critical information with the official CPMAI handbook."
    )
